# Gradle ??
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin ??
kotlin.code.style=official
kotlin.incremental=true
kotlin.parallel.tasks.in.project=true

# Kapt ??
kapt.use.worker.api=true
kapt.incremental.apt=true
kapt.include.compile.classpath=false

# ?? AndroidX
android.useAndroidX=true
# ????????? AndroidX
android.enableJetifier=true